FROM jupyter/minimal-notebook:latest

USER root

RUN pip install --no-cache-dir \
    mlflow \
    boto3 \
    psycopg2-binary \
    scikit-learn \
    transformers \
    datasets \
    pytest \
    dvc \
    dvc-s3 \
    torch --index-url https://download.pytorch.org/whl/cpu

USER jovyan